server:
  port: 8002
  
eureka:
  client:
   service-url:
      #客户端注册到单机服务器中 defaultZone: http://localhost:8080/eureka
      #客户端注册到集群版服务器中
     defaultZone: http://h1:8070/eureka/,http://h2:8080/eureka/,http://h3:8090/eureka/