server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.wbd.aip.pojo    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    

    
spring:
   application:
    name: microservice-provider-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://118.190.71.215:3306/project              # 数据库名称
    username: rmtuser
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
#客户端注册到 eureka的服务器
eureka:
  client:
   service-url:
      #客户端注册到单机服务器中 defaultZone: http://localhost:8080/eureka
      #客户端注册到集群版服务器中
     defaultZone: http://h1:8070/eureka/,http://h2:8080/eureka/,http://h3:8090/eureka/
  #instance:
   #  instance-id: microservice-provider-dept8001 #自定义服务器名称
   #  prefer-ip-address: true #访问路径显示ip地址
      
info:
   app.name: microservice-provider-dept8001
   company.name: http://www.wanbeidai.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
   
       
      