server:
  port: 8080
  
eureka:
  instance: 
    hostname: localhost #eureka实例名称
    
  client:
   register-with-eureka: false  #服务中心不需要注册其他地方，客户端才需要注册到服务中心,默认为true,即为客户端，需要注册
   fetch-registry: false #表示自己就是注册中心，我的职责是维护实例，不是去检索服务
   service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
     #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    
   
 